// Code generated by 'go run ./gen'. DO NOT EDIT
package main

import (
	"github.com/bottino/aoc2024/day01"
	"github.com/bottino/aoc2024/day02"
	"github.com/bottino/aoc2024/day03"
	"github.com/bottino/aoc2024/day04"
	"github.com/bottino/aoc2024/day05"
	"github.com/bottino/aoc2024/day06"
	"github.com/bottino/aoc2024/day07"
	"github.com/bottino/aoc2024/day08"
	"github.com/bottino/aoc2024/day09"
	"github.com/bottino/aoc2024/day10"
	"github.com/bottino/aoc2024/day11"
	"github.com/bottino/aoc2024/day12"
	"github.com/bottino/aoc2024/day13"
)

var days = map[int]aocDay{
	1: {1, day01.Part1, day01.Part2},
	2: {2, day02.Part1, day02.Part2},
	3: {3, day03.Part1, day03.Part2},
	4: {4, day04.Part1, day04.Part2},
	5: {5, day05.Part1, day05.Part2},
	6: {6, day06.Part1, day06.Part2},
	7: {7, day07.Part1, day07.Part2},
	8: {8, day08.Part1, day08.Part2},
	9: {9, day09.Part1, day09.Part2},
	10: {10, day10.Part1, day10.Part2},
	11: {11, day11.Part1, day11.Part2},
	12: {12, day12.Part1, day12.Part2},
	13: {13, day13.Part1, day13.Part2},
}
